window.AJAY_NXT_DEFAULT_CONTENT = {
  hero:{eyebrow:'Websites · Apps · Motion · Growth',role:'Web developer, app builder and digital creator.',ledeV3:'I create refined digital experiences that make businesses look credible, clear and ready to grow.'},
  about:{headingV3:'Design sense, engineering discipline and visual storytelling in one studio.',bodyV3:'I’m Ajay Saini. I help businesses turn rough ideas into clear, polished digital experiences.'},
  projects:{diamond:{title:'Diamond Restaurants',eyebrow:'Restaurant website + admin system',summary:'A premium customer website with responsive menus and practical content control.',challenge:'Present a large restaurant, bakery and sweets catalogue without making the experience feel crowded.',solution:'A responsive brand system with clear navigation, mobile-first layouts and admin-managed content.',result:'A polished live website with organised menu content and a practical day-to-day update system.',services:['UI direction','Responsive development','Firebase admin','SEO & deployment'],url:'https://diamondrestaurants.com/'},rajmahal:{title:'Rajmahal Palace',eyebrow:'Luxury hospitality demo',summary:'A cinematic hospitality direction showing premium web capability.',challenge:'Create a fictional palace experience that feels luxurious without becoming slow or visually noisy.',solution:'Editorial typography, restrained motion and immersive imagery shaped around a booking journey.',result:'A live hospitality demo demonstrating design, development and motion direction.',services:['Creative direction','Web design','Motion design','Frontend development'],url:'https://rajmahal.ajaynxt.com/'}},
  websites:[
    {id:'diamond-restaurants',type:'client',priority:1,category:'Restaurant',label:'Live client project',title:'Diamond Restaurants',summary:'Premium restaurant, bakery and sweets website with responsive menus and Firebase content control.',image:'./assets/photo-food-diamond.webp',imageAlt:'Diamond Restaurants client website and food presentation',url:'https://diamondrestaurants.com/',caseStudy:'diamond',tags:['Live website','Firebase admin','Restaurant experience'],published:true,previewAccent:'#e9bd72'},
    {id:'demo-rajmahal',type:'demo',priority:1,category:'Hospitality',label:'Palace hotel & hospitality',title:'Rajmahal',summary:'Royal hospitality direction for rooms, dining, celebrations, heritage storytelling and bookings.',image:'./assets/rajmahal-demo-preview.jpg',imageAlt:'Rajmahal palace hotel demo preview',url:'https://rajmahal.ajaynxt.com/',caseStudy:'rajmahal',tags:['Rooms','Dining','Celebrations'],published:true,previewAccent:'#e9bd72'},
    {id:'demo-jewellery',type:'demo',priority:2,category:'Luxury retail',label:'Jewellery & fine retail',title:'Jewellery',summary:'Luxury product storytelling for rings, collections, trust and direct purchase enquiries.',image:'',imageAlt:'Luxury jewellery website demo',url:'https://jewellery.ajaynxt.com/#rings',tags:['Rings','Collections','Luxury retail'],published:true,previewTitle:'Fine Jewellery',previewAccent:'#e8c885',previewBg:'#15110d'},
    {id:'demo-gym',type:'demo',priority:3,category:'Health & fitness',label:'Gym & fitness club',title:'Gym',summary:'Membership-focused website with programmes, offers and lead actions.',image:'',url:'https://gym.ajaynxt.com/',tags:['Memberships','Programmes','Lead generation'],published:true,previewAccent:'#d5ff34',previewBg:'#111410'},
    {id:'demo-biomech',type:'demo',priority:4,category:'Health & technology',label:'Biomechanics & medtech',title:'Biomech',summary:'Motion science and medical technology presentation with interactive hero styles.',image:'./assets/biomech-demo-preview.webp',url:'https://biomech.ajaynxt.com/',tags:['Medtech','Product story','Interactive'],published:true,previewAccent:'#73d8ff'},
    {id:'demo-dental',type:'demo',priority:5,category:'Healthcare',label:'Dental clinic',title:'Dental',summary:'Clean healthcare website for treatments, appointments, trust and patient communication.',image:'./assets/dental-demo-preview.png',url:'https://dental.ajaynxt.com/',tags:['Appointments','Treatments','Patient trust'],published:true,previewAccent:'#72d2ff'},
    {id:'demo-saas',type:'demo',priority:6,category:'Technology',label:'SaaS & software platform',title:'SaaS',summary:'Modern product website with analytics, feature storytelling and conversion sections.',image:'',url:'https://saas.ajaynxt.com/',tags:['Product UI','Analytics','Conversion'],published:true,previewAccent:'#8da7ff',previewBg:'#10131d'},
    {id:'demo-store',type:'demo',priority:7,category:'Commerce',label:'E-commerce store',title:'Store',summary:'Product-led shopping interface designed for collections, offers and purchase intent.',image:'',url:'https://store.ajaynxt.com/',tags:['Collections','Offers','Shopping'],published:true,previewAccent:'#ff9f7a',previewBg:'#1a1110'},
    {id:'demo-architect',type:'demo',priority:8,category:'Spaces',label:'Architecture & interiors',title:'Architect',summary:'Editorial portfolio for architecture, interiors, project stories and enquiries.',image:'',url:'https://interior.ajaynxt.com/',tags:['Portfolio','Interiors','Enquiries'],published:true,previewAccent:'#d4c2a5',previewBg:'#141310'},
    {id:'demo-travel',type:'demo',priority:9,category:'Travel',label:'Travel & tours',title:'Travel',summary:'Destination-first travel experience with packages, highlights and booking prompts.',image:'',url:'https://travel.ajaynxt.com/',tags:['Destinations','Packages','Bookings'],published:true,previewAccent:'#72d5c8',previewBg:'#0d1817'},
    {id:'demo-salon',type:'demo',priority:10,category:'Beauty',label:'Beauty salon & spa',title:'Salon',summary:'Elegant appointment website for beauty services, packages, pricing and trust.',image:'',url:'https://salon.ajaynxt.com/',tags:['Appointments','Services','Pricing'],published:true,previewAccent:'#ffb1cb',previewBg:'#1d1117'},
    {id:'demo-academy',type:'demo',priority:11,category:'Education',label:'Education & academy',title:'Academy',summary:'Course discovery website with a photo-first hero and programme details.',image:'',url:'https://academy.ajaynxt.com/',tags:['Courses','Programmes','Enrolment'],published:true,previewAccent:'#ffd66e',previewBg:'#18150c'},
    {id:'demo-wedding',type:'demo',priority:12,category:'Events',label:'Wedding planner & events',title:'Wedding',summary:'Luxury celebration website for planning, galleries, packages and availability enquiries.',image:'',url:'https://wedding.ajaynxt.com/',tags:['Galleries','Packages','Availability'],published:true,previewAccent:'#e5b6ff',previewBg:'#1a101d'},
    {id:'demo-estate',type:'demo',priority:13,category:'Property',label:'Real estate & property',title:'Estate',summary:'Premium property showcase with search, listings, EMI tools and visit enquiries.',image:'',url:'https://estate.ajaynxt.com/',tags:['Search','Listings','Site visits'],published:true,previewAccent:'#b8d6ff',previewBg:'#0f151b'},
    {id:'demo-logistics',type:'demo',priority:14,category:'Business',label:'Logistics & freight',title:'Logistics',summary:'B2B logistics presentation for freight services, quote requests and shipment workflows.',image:'./assets/logistics-demo-preview.png',url:'https://logistics.ajaynxt.com/',tags:['Freight','Quotes','Tracking'],published:true,previewAccent:'#6ea8ff'},
    {id:'demo-hub',type:'demo',priority:15,category:'Showcase',label:'Multi-industry showcase',title:'Demo Hub',summary:'A central presentation hub for browsing multiple design directions by industry.',image:'',url:'https://demos.ajaynxt.com/',tags:['Industry filters','Client presentation'],published:true,previewAccent:'#c9ff38'},
    {id:'demo-auto',type:'demo',priority:16,category:'Automotive',label:'Automobile dealership',title:'Auto',summary:'Vehicle-focused experience for models, specifications, finance and test-drive enquiries.',image:'',url:'https://auto.ajaynxt.com/',tags:['Models','Finance','Test drive'],published:true,previewAccent:'#ff7c63',previewBg:'#1b0e0b'},
    {id:'demo-legal',type:'demo',priority:17,category:'Professional',label:'Law firm & legal services',title:'Legal',summary:'Professional legal website built around practice areas, credibility and consultation actions.',image:'',url:'https://legal.ajaynxt.com/',tags:['Practice areas','Credibility','Consultation'],published:true,previewAccent:'#d8c699',previewBg:'#17150f'},
    {id:'demo-clinic',type:'demo',priority:18,category:'Healthcare',label:'Healthcare clinic',title:'Clinic',summary:'Approachable clinic website for services, doctors, appointments and patient confidence.',image:'',url:'https://clinic.ajaynxt.com/',tags:['Doctors','Appointments','Patient confidence'],published:true,previewAccent:'#78d7be',previewBg:'#0d1815'},
    {id:'demo-fitness',type:'demo',priority:19,category:'Health & fitness',label:'Fitness coach & studio',title:'Fitness',summary:'Personal fitness website for programmes, coaching, transformations and lead generation.',image:'',url:'https://fitness.ajaynxt.com/',tags:['Coaching','Transformations','Leads'],published:true,previewAccent:'#c9ff38',previewBg:'#10140c'},
    {id:'demo-restaurant',type:'demo',priority:20,category:'Hospitality',label:'Restaurant & dining',title:'Restaurant',summary:'Food-forward restaurant presentation for menu discovery, ambience and reservations.',image:'./assets/photo-food-diamond.webp',url:'https://restaurant.ajaynxt.com/',tags:['Menu','Ambience','Reservations'],published:true,previewAccent:'#ff9e65'},
    {id:'demo-diamond',type:'demo',priority:21,category:'Hospitality',label:'Restaurant presentation',title:'Diamond Restaurant Demo',summary:'Restaurant direction for menu presentation, dining ambience and reservations.',image:'./assets/photo-food-diamond.webp',url:'https://diamond.ajaynxt.com/',tags:['Menu','Dining','Reservations'],published:true,previewAccent:'#e9bd72'}
  ],
  social:{instagram:'https://www.instagram.com/ajay_nxt_/',linkedin:'https://www.linkedin.com/in/ajaynxt/',threads:'https://www.threads.com/@ajay_nxt_',facebook:'https://www.facebook.com/share/1JEe6e7LYB/',whatsapp:'https://wa.me/919929562585',email:'mailto:ajayx3neha@gmail.com',phone:'tel:+919929562585',github:'',youtube:''},
  appearance:{headingFont:'cormorant',paletteStart:'lime',motionLevel:'subtle'},
  settings:{designVersion:5.01,paletteRotationEnabled:true,paletteDelayMs:2000,headingRotationEnabled:true}
};
window.AJAY_NXT_MEDIA={
  videos:[
    {driveId:'1rHtR4uG8tW_JgPfMrMwH-0p_Bz6WKB-9',poster:'./assets/posters/film-01-wedding-song.webp',title:'Wedding Song Film',category:'Wedding film',duration:'00:24'},
    {driveId:'1OEKC3RiGv8VMj5-l7efxxqF9F2RHFBvM',poster:'./assets/posters/film-02-family-moments.webp',title:'Family Wedding Moments',category:'Emotion & story',duration:'00:35'},
    {driveId:'1HdqCYTuI7mgjj67ebeQuyUjHVJKaHq6a',poster:'./assets/posters/film-03-mehndi-bride.webp',title:'Mehndi Bride Story',category:'Bridal cinematic',duration:'02:50'},
    {driveId:'1VuNVLgf-9GpYKxKxCJ0Vq1yvis03Uwa_',poster:'./assets/posters/film-04-haldi.webp',title:'Haldi Celebration',category:'Celebration energy',duration:'00:46'},
    {driveId:'1FXb2XyF0sv6iQj5IwKAJqvDlKHIricwn',poster:'./assets/posters/film-05-guest-entry.webp',title:'Guest Entry Film',category:'Event momentum',duration:'00:33'},
    {driveId:'1qy1_MYpCxCqJQeyXoXspevioKa_QUF3O',poster:'./assets/posters/film-06-cinematic-song.webp',title:'Cinematic Wedding Song',category:'Visual flow',duration:'00:51'},
    {driveId:'1AsaZtcogvHMDCtarn8eENBBNCm5xFDJ4',poster:'./assets/posters/film-07-wedding-song-two.webp',title:'Wedding Story Edit',category:'Story & colour grade',duration:'00:49'},
    {driveId:'1VuULcRrXVhrOJSp4ifPdBqkmntrJXa9h',poster:'./assets/posters/film-08-final-timeline.webp',title:'Final Timeline Cut',category:'Timing & delivery',duration:'00:27'},
    {driveId:'1yWpUlrZkoxkRhtDMDUwH_RcU0PylV5HQ',poster:'./assets/posters/film-09-selected-wedding-film.webp',title:'Selected Wedding Film',category:'Wedding highlight',duration:'01:37'},
    {localUrl:'./assets/videos/film-10-vn-wedding-film.mp4',poster:'./assets/posters/film-10-vn-wedding-film.webp',title:'Wedding Highlight',category:'Cinematic highlight',duration:'01:41'}
  ],
  photos:[
    {image:'./assets/photo-product-studio.webp',label:'Product retouching',title:'Clean commercial finish'},
    {image:'./assets/photo-food-diamond.webp',label:'Food & hospitality',title:'Real brand presentation'},
    {image:'./assets/photo-editing-studio.webp',label:'Creative editing',title:'Retouching and compositing'},
    {image:'./assets/ajay-hero-color-embedded.webp',label:'Portrait treatment',title:'Controlled colour and contrast'},
    {image:'./assets/posters/film-03-mehndi-bride.webp',label:'Editorial frame',title:'Story-led visual treatment'}
  ]
};
