window.AJAY_NXT_DEFAULT_CONTENT = {
  hero: {
    eyebrow: 'Websites · Apps · Motion · Growth',
    lineOne: 'Web developer, app builder and digital creator.',
    role: 'Web developer, app builder and digital creator.',
    lineTwo: 'AJAY NXT',
    highlight: 'Work that carries business weight.',
    lede: 'I create premium digital experiences that help businesses look professional, earn trust and grow.',
    ledeV3: 'I create premium digital experiences that help businesses look professional, earn trust and grow.'
  },
  about: {
    heading: 'Design sense, engineering discipline and visual storytelling in one studio.',
    headingV3: 'Design sense, engineering discipline and visual storytelling in one studio.',
    body: 'I’m Ajay Saini. I help businesses turn rough ideas into clear, polished digital experiences.',
    bodyV3: 'I’m Ajay Saini. I help businesses turn rough ideas into clear, polished digital experiences.'
  },
  review: {
    label: 'Diamond Restaurants',
    quote: 'Premium, responsive and easy to manage. Ajay understood our requirements and delivered a website that represents Diamond Restaurants professionally.',
    name: 'Aman Sharma', company: 'Diamond Restaurants', rating: '5.0',
    proofUrl: 'https://diamondrestaurants.com/', proofLabel: 'View project', published: true
  },
  reviews: [{id:'diamond-restaurants',label:'Diamond Restaurants',quote:'Premium, responsive and easy to manage. Ajay understood our requirements and delivered a website that represents Diamond Restaurants professionally.',name:'Aman Sharma',company:'Diamond Restaurants',rating:'5.0',proofUrl:'https://diamondrestaurants.com/',proofLabel:'View project',published:true}],
  projects: {
    diamond:{title:'Diamond Restaurants',eyebrow:'Restaurant website + admin system',summary:'A premium customer website with responsive menus and practical content control.',challenge:'Present a large restaurant, bakery and sweets catalogue without making the experience feel crowded.',solution:'A responsive brand system with clear navigation, mobile-first layouts and admin-managed content.',result:'A polished live website with organised menu content and a practical day-to-day update system.',services:['UI direction','Responsive development','Firebase admin','SEO & deployment'],url:'https://diamondrestaurants.com/'},
    weddingShedding:{title:'Wedding Shedding',eyebrow:'Wedding media collaboration',summary:'Photography, film and digital presentation for celebrations across India.',challenge:'Present emotional visual work without burying it under decorative effects.',solution:'A cinematic but restrained presentation built around real photography, films and clear enquiry links.',result:'A live collaboration website that connects visual proof with direct business enquiries.',services:['Website presentation','Video portfolio','Responsive experience','Social integration'],url:'https://weddingshedding.github.io/._/'},
    moveToGo:{title:'Move To Go',eyebrow:'Mobility product concept',summary:'A connected product direction for customers, riders and operations.',challenge:'Simplify ride and parcel workflows across customer, rider and admin experiences.',solution:'Role-based journeys, live status and practical operations controls.',result:'A product architecture ready for staged app development.',services:['Product structure','App experience','Rider flow','Admin dashboard'],url:''},
    rajmahal:{title:'Rajmahal Palace',eyebrow:'Luxury hospitality demo',summary:'A cinematic hospitality direction showing premium web capability.',challenge:'Create a fictional palace experience that feels luxurious without becoming slow or visually noisy.',solution:'Editorial typography, restrained motion and immersive imagery shaped around a booking journey.',result:'A live hospitality demo demonstrating design, development and motion direction.',services:['Creative direction','Web design','Motion design','Frontend development'],url:'https://rajmahal.ajaynxt.com/'}
  },
  websites: [
    {id:'diamond-restaurants',type:'client',priority:1,featured:true,year:'2026',category:'Restaurant',label:'Live client project',title:'Diamond Restaurants',summary:'Premium restaurant, bakery and sweets website with responsive menus and Firebase content control.',image:'./assets/photo-food-diamond.webp',imageAlt:'Diamond Restaurants client website and food presentation',url:'https://diamondrestaurants.com/',caseStudy:'diamond',tags:['Live website','Firebase admin','Restaurant experience'],published:true},
    {id:'wedding-shedding-client',type:'client',priority:2,featured:true,year:'Live',category:'Wedding',label:'Live collaboration',title:'Wedding Shedding',summary:'Wedding photography, films and digital presentation built around real visual work and direct enquiries.',image:'./assets/collaboration/wedding-shedding-capture.webp',imageAlt:'Wedding Shedding collaboration website preview',url:'https://weddingshedding.github.io/._/',caseStudy:'weddingShedding',tags:['Photography','Wedding films','Digital experience'],published:true},

    {id:'demo-gym',type:'demo',priority:1,styleCount:1,category:'Health & Fitness',label:'Gym & fitness club',title:'Gym',summary:'Membership-focused website with programmes, offers and lead actions.',image:'',imageAlt:'Gym website demo',url:'https://gym.ajaynxt.com/',caseStudy:'',tags:['Memberships','Programmes','Lead generation'],published:true},
    {id:'demo-biomech',type:'demo',priority:2,styleCount:1,category:'Health & Technology',label:'Biomechanics & medtech',title:'Biomech',summary:'Motion science and medical technology presentation with interactive hero styles.',image:'./assets/biomech-demo-preview.webp',imageAlt:'Biomech medical technology demo preview',url:'https://biomech.ajaynxt.com/',caseStudy:'',tags:['Medtech','Product story','Interactive'],published:true},
    {id:'demo-dental',type:'demo',priority:3,styleCount:1,category:'Healthcare',label:'Dental clinic',title:'Dental',summary:'Clean healthcare website for treatments, appointments, trust and patient communication.',image:'./assets/dental-demo-preview.png',imageAlt:'Dental clinic demo preview',url:'https://dental.ajaynxt.com/',caseStudy:'',tags:['Appointments','Treatments','Patient trust'],published:true},
    {id:'demo-saas',type:'demo',priority:4,styleCount:1,category:'Technology',label:'SaaS & software',title:'SaaS',summary:'Modern product website with analytics, feature storytelling and conversion sections.',image:'',imageAlt:'SaaS software website demo',url:'https://saas.ajaynxt.com/',caseStudy:'',tags:['Product UI','Analytics','Conversion'],published:true},
    {id:'demo-store',type:'demo',priority:5,styleCount:1,category:'Commerce',label:'E-commerce store',title:'Store',summary:'Product-led shopping interface designed for collections, offers and purchase intent.',image:'',imageAlt:'E-commerce store demo',url:'https://store.ajaynxt.com/',caseStudy:'',tags:['Collections','Offers','Shopping'],published:true},
    {id:'demo-architect',type:'demo',priority:6,styleCount:1,category:'Spaces',label:'Architecture & interiors',title:'Architect',summary:'Editorial portfolio for architecture, interiors, project stories and enquiries.',image:'',imageAlt:'Architecture and interior design demo',url:'https://interior.ajaynxt.com/',caseStudy:'',tags:['Portfolio','Interiors','Enquiries'],published:true},
    {id:'demo-travel',type:'demo',priority:7,styleCount:1,category:'Travel',label:'Travel & tours',title:'Travel',summary:'Destination-first travel experience with packages, highlights and booking prompts.',image:'',imageAlt:'Travel and tour agency demo',url:'https://travel.ajaynxt.com/',caseStudy:'',tags:['Destinations','Packages','Bookings'],published:true},
    {id:'demo-salon',type:'demo',priority:8,styleCount:1,category:'Beauty',label:'Beauty salon & spa',title:'Salon',summary:'Elegant appointment website for beauty services, packages, pricing and trust.',image:'',imageAlt:'Beauty salon and spa demo',url:'https://salon.ajaynxt.com/',caseStudy:'',tags:['Appointments','Services','Pricing'],published:true},
    {id:'demo-academy',type:'demo',priority:9,styleCount:1,category:'Education',label:'Education & academy',title:'Academy',summary:'Course discovery website with a photo-first hero and programme details.',image:'',imageAlt:'Education and online academy demo',url:'https://academy.ajaynxt.com/',caseStudy:'',tags:['Courses','Programmes','Enrolment'],published:true},
    {id:'demo-wedding',type:'demo',priority:10,styleCount:1,category:'Events',label:'Wedding planner & events',title:'Wedding',summary:'Luxury celebration website for planning, galleries, packages and availability enquiries.',image:'',imageAlt:'Wedding planner and events demo',url:'https://wedding.ajaynxt.com/',caseStudy:'',tags:['Galleries','Packages','Availability'],published:true},
    {id:'demo-estate',type:'demo',priority:11,styleCount:1,category:'Property',label:'Real estate & property',title:'Estate',summary:'Premium property showcase with search, listings, EMI tools and visit enquiries.',image:'',imageAlt:'Real estate property demo',url:'https://estate.ajaynxt.com/',caseStudy:'',tags:['Search','Listings','Site visits'],published:true},
    {id:'demo-logistics',type:'demo',priority:12,styleCount:1,category:'Business',label:'Logistics & freight',title:'Logistic',summary:'B2B logistics presentation for freight services, quote requests and shipment workflows.',image:'./assets/logistics-demo-preview.png',imageAlt:'Logistics and freight demo preview',url:'https://logistics.ajaynxt.com/',caseStudy:'',tags:['Freight','Quotes','Tracking'],published:true},
    {id:'demo-hub',type:'demo',priority:13,styleCount:1,category:'Showcase',label:'Multi-industry showcase',title:'Client Demo Hub',summary:'A central presentation hub for browsing multiple design directions by industry.',image:'',imageAlt:'AJAY NXT demo showcase hub',url:'https://demos.ajaynxt.com/',caseStudy:'',tags:['20 websites','Industry filters','Client presentation'],published:true},
    {id:'demo-auto',type:'demo',priority:14,styleCount:1,category:'Automotive',label:'Automobile dealership',title:'Auto',summary:'Vehicle-focused experience for models, specifications, finance and test-drive enquiries.',image:'',imageAlt:'Automobile and car dealership demo',url:'https://auto.ajaynxt.com/',caseStudy:'',tags:['Models','Finance','Test drives'],published:true},
    {id:'demo-legal',type:'demo',priority:15,styleCount:1,category:'Professional',label:'Law firm & legal services',title:'Legal',summary:'Professional legal website built around practice areas, credibility and consultations.',image:'',imageAlt:'Law firm and legal services demo',url:'https://legal.ajaynxt.com/',caseStudy:'',tags:['Practice areas','Credibility','Consultations'],published:true},
    {id:'demo-clinic',type:'demo',priority:16,styleCount:1,category:'Healthcare',label:'Healthcare clinic',title:'Clinic',summary:'Approachable clinic website for services, doctors, appointments and patient confidence.',image:'',imageAlt:'Healthcare clinic demo',url:'https://clinic.ajaynxt.com/',caseStudy:'',tags:['Doctors','Appointments','Patient care'],published:true},
    {id:'demo-fitness',type:'demo',priority:17,styleCount:1,category:'Health & Fitness',label:'Fitness coach & studio',title:'Fitness',summary:'Personal fitness website for programmes, coaching, transformations and lead generation.',image:'',imageAlt:'Fitness coach and studio demo',url:'https://fitness.ajaynxt.com/',caseStudy:'',tags:['Coaching','Transformations','Leads'],published:true},
    {id:'demo-restaurant',type:'demo',priority:18,styleCount:1,category:'Hospitality',label:'Restaurant & dining',title:'Restaurant',summary:'Food-forward restaurant presentation for menu discovery, ambience and reservations.',image:'',imageAlt:'Restaurant and dining website demo',url:'https://restaurant.ajaynxt.com/',caseStudy:'',tags:['Menu','Ambience','Reservations'],published:true},
    {id:'demo-rajmahal',type:'demo',priority:19,styleCount:1,category:'Hospitality',label:'Palace hotel & hospitality',title:'Rajmahal',summary:'Royal hospitality concept for rooms, dining, celebrations and booking journeys.',image:'./assets/rajmahal-demo-preview.jpg',imageAlt:'Rajmahal palace hotel demo preview',url:'https://rajmahal.ajaynxt.com/',caseStudy:'rajmahal',tags:['Luxury','Heritage','Bookings'],published:true},
    {id:'demo-diamond',type:'demo',priority:20,styleCount:1,category:'Hospitality',label:'Restaurant presentation',title:'Diamond Restaurant',summary:'Restaurant website direction for menu presentation, dining ambience and reservations.',image:'./assets/photo-food-diamond.webp',imageAlt:'Diamond Restaurant website demo preview',url:'https://diamond.ajaynxt.com/',caseStudy:'',tags:['Menu','Dining','Reservations'],published:true}
  ],
  social:{instagram:'https://www.instagram.com/ajay_nxt_/',linkedin:'https://www.linkedin.com/in/ajaynxt/',threads:'https://www.threads.com/@ajay_nxt_',facebook:'https://www.facebook.com/share/1JEe6e7LYB/',whatsapp:'https://wa.me/919929562585',email:'mailto:ajayx3neha@gmail.com',phone:'tel:+919929562585',github:'',youtube:''},
  appearance:{headingFont:'cormorant',paletteStart:'ember',motionLevel:'subtle'},
  settings:{paletteRotationEnabled:true,paletteDelayMs:180000,headingRotationEnabled:false}
};
