window.AJAY_NXT_DEFAULT_CONTENT = {
  hero: {
    eyebrow: 'Websites · Apps · Motion · Growth',
    lineOne: 'Web developer, app builder and digital creator.',
    role: 'Web developer, app builder and digital creator.',
    lineTwo: 'AJAY NXT',
    highlight: 'Work that carries business weight.',
    lede: 'I create premium digital experiences that help businesses look professional, earn trust and grow.',
    ledeV3: 'I create premium digital experiences that help businesses look professional, earn trust and grow.'
  },
  about: {
    heading: 'Design sense, engineering discipline and visual storytelling in one studio.',
    headingV3: 'Design sense, engineering discipline and visual storytelling in one studio.',
    body: 'I’m Ajay Saini. I help businesses turn rough ideas into clear, polished digital experiences.',
    bodyV3: 'I’m Ajay Saini. I help businesses turn rough ideas into clear, polished digital experiences.'
  },
  review: {
    label: 'Diamond Restaurants',
    quote: 'Premium, responsive and easy to manage. Ajay understood our requirements and delivered a website that represents Diamond Restaurants professionally.',
    name: 'Aman Sharma', company: 'Diamond Restaurants', rating: '5.0',
    proofUrl: 'https://diamondrestaurants.com/', proofLabel: 'View project', published: true
  },
  reviews: [{id:'diamond-restaurants',label:'Diamond Restaurants',quote:'Premium, responsive and easy to manage. Ajay understood our requirements and delivered a website that represents Diamond Restaurants professionally.',name:'Aman Sharma',company:'Diamond Restaurants',rating:'5.0',proofUrl:'https://diamondrestaurants.com/',proofLabel:'View project',published:true}],
  projects: {
    diamond:{title:'Diamond Restaurants',eyebrow:'Restaurant website + admin system',summary:'A premium customer website with responsive menus and practical content control.',challenge:'Present a large restaurant, bakery and sweets catalogue without making the experience feel crowded.',solution:'A responsive brand system with clear navigation, mobile-first layouts and admin-managed content.',result:'A polished live website with organised menu content and a practical day-to-day update system.',services:['UI direction','Responsive development','Firebase admin','SEO & deployment'],url:'https://diamondrestaurants.com/'},
    weddingShedding:{title:'Wedding Shedding',eyebrow:'Wedding media collaboration',summary:'Photography, film and digital presentation for celebrations across India.',challenge:'Present emotional visual work without burying it under decorative effects.',solution:'A cinematic but restrained presentation built around real photography, films and clear enquiry links.',result:'A live collaboration website that connects visual proof with direct business enquiries.',services:['Website presentation','Video portfolio','Responsive experience','Social integration'],url:'https://weddingshedding.github.io/._/'},
    moveToGo:{title:'Move To Go',eyebrow:'Mobility product concept',summary:'A connected product direction for customers, riders and operations.',challenge:'Simplify ride and parcel workflows across customer, rider and admin experiences.',solution:'Role-based journeys, live status and practical operations controls.',result:'A product architecture ready for staged app development.',services:['Product structure','App experience','Rider flow','Admin dashboard'],url:''},
    rajmahal:{title:'Rajmahal Palace',eyebrow:'Luxury hospitality demo',summary:'A cinematic hospitality direction showing premium web capability.',challenge:'Create a fictional palace experience that feels luxurious without becoming slow or visually noisy.',solution:'Editorial typography, restrained motion and immersive imagery shaped around a booking journey.',result:'A live hospitality demo demonstrating design, development and motion direction.',services:['Creative direction','Web design','Motion design','Frontend development'],url:'https://rajmahal.ajaynxt.com/'}
  },
  websites: [
    {id:'diamond-restaurants',type:'client',priority:1,featured:true,year:'2026',category:'Restaurant',label:'Client project',title:'Diamond Restaurants',summary:'Premium restaurant, bakery and sweets website with responsive menus and Firebase content control.',image:'./assets/photo-food-diamond.webp',imageAlt:'Diamond Restaurants client website and food presentation',url:'https://diamondrestaurants.com/',caseStudy:'diamond',tags:['Live client work','Firebase admin','Restaurant experience'],published:true},
    {id:'wedding-shedding-client',type:'client',priority:2,featured:true,year:'Live',category:'Wedding',label:'Collaboration',title:'Wedding Shedding',summary:'Wedding photography, films and digital presentation built around real visual work and direct enquiries.',image:'./assets/collaboration/wedding-shedding-capture.webp',imageAlt:'Wedding Shedding collaboration website preview',url:'https://weddingshedding.github.io/._/',caseStudy:'weddingShedding',tags:['Photography','Wedding films','Digital experience'],published:true},
    {id:'rajmahal-palace',type:'demo',priority:1,styleCount:1,category:'Hospitality',label:'Luxury hospitality demo',title:'Rajmahal Palace',summary:'A cinematic palace-hotel concept shaped with editorial design and restrained motion.',image:'./assets/rajmahal-demo-preview.jpg',imageAlt:'Rajmahal Palace luxury hospitality demo preview',url:'https://rajmahal.ajaynxt.com/',caseStudy:'rajmahal',tags:['Luxury direction','Booking journey','Motion'],published:true},
    {id:'ironpulse-gym',type:'demo',priority:2,styleCount:1,category:'Fitness',label:'Fitness business demo',title:'IRONPULSE Fitness Club',summary:'A conversion-focused gym website with memberships, trainers, supplements and free-trial enquiries.',image:'https://images.pexels.com/photos/35609526/pexels-photo-35609526.jpeg?auto=compress&cs=tinysrgb&w=1200',imageAlt:'IRONPULSE gym website demo preview',url:'https://gym.ajaynxt.com/#top',caseStudy:'',tags:['Memberships','Free trials','Trainer profiles'],published:true},
    {id:'dental-design-studio',type:'demo',priority:3,styleCount:3,category:'Healthcare',label:'Dental clinic demo',title:'Dental Design Studio',summary:'Three responsive clinic directions with booking, services and live visual controls.',image:'./assets/dental-demo-preview.png',imageAlt:'Dental Design Studio demo preview',url:'https://dental.ajaynxt.com/',caseStudy:'',tags:['3 concepts','Clinic booking','Live customizer'],published:true},
    {id:'movegrid-logistics',type:'demo',priority:4,styleCount:10,category:'Logistics',label:'Logistics demo',title:'MOVEGRID Logistics',summary:'Ten business-ready directions with freight quotes, shipment tracking and operational flows.',image:'./assets/logistics-demo-preview.png',imageAlt:'MOVEGRID logistics demo preview',url:'https://logistics.ajaynxt.com/',caseStudy:'',tags:['10 visual styles','Freight quotes','Tracking'],published:true},
    {id:'nexora-biomech',type:'demo',priority:5,styleCount:7,category:'Medical Tech',label:'Medical technology demo',title:'Nexora Biomech',summary:'Seven responsive directions for prosthetics, medical robotics and clinical research.',image:'./assets/biomech-demo-preview.webp',imageAlt:'Nexora Biomech demo preview',url:'https://biomech.ajaynxt.com/',caseStudy:'',tags:['7 visual styles','Product story','Care pathway'],published:true},
    {id:'estara-properties',type:'demo',priority:6,styleCount:10,category:'Real Estate',label:'Property portal demo',title:'Estara Properties',summary:'Ten property directions with search, virtual tours, EMI planning and site-visit enquiries.',image:'https://images.pexels.com/photos/30506378/pexels-photo-30506378.jpeg?auto=compress&cs=tinysrgb&w=1400',imageAlt:'Estara Properties real estate demo preview',url:'https://estate.ajaynxt.com/',caseStudy:'',tags:['10 visual styles','Property search','Site visits'],published:true},
    {id:'vow-and-frame-weddings',type:'demo',priority:7,styleCount:10,category:'Wedding',label:'Wedding studio demo',title:'Vow & Frame Weddings',summary:'Ten wedding directions with stories, films, packages, availability and WhatsApp enquiries.',image:'https://images.pexels.com/photos/33485965/pexels-photo-33485965.jpeg?auto=compress&cs=tinysrgb&w=1400',imageAlt:'Vow and Frame wedding demo preview',url:'https://wedding.ajaynxt.com/',caseStudy:'',tags:['10 visual styles','Wedding films','Date booking'],published:true}
  ],
  social:{instagram:'https://www.instagram.com/ajay_nxt_/',linkedin:'https://www.linkedin.com/in/ajaynxt/',threads:'https://www.threads.com/@ajay_nxt_',facebook:'https://www.facebook.com/share/1JEe6e7LYB/',whatsapp:'https://wa.me/919929562585',email:'mailto:ajayx3neha@gmail.com',phone:'tel:+919929562585',github:'',youtube:''},
  appearance:{headingFont:'cormorant',paletteStart:'ember',motionLevel:'subtle'},
  settings:{paletteRotationEnabled:true,paletteDelayMs:180000,headingRotationEnabled:false}
};
